### ISSUE TITLE
The SDK ran out of memory (Android 8.0, Samsung Galaxy S9)

### ISSUE THREAD

**Issue by markusrubey** [chirp/chirp-android-examples#5] opened 2019-02-21 22:10 UTC
I'm running out of memory on my Samsung Galaxy S9 every time I press 'START SDK' in the Demo app.

SDK Version: Chirp Connect 3.6.0-beta [3.2.5 955]
Android Version: 8.0.0
Phone: Samsung Galaxy S9 (SM-G960F)

Log:
[chirp_demo_crash_log.txt](https://github.com/chirp/chirp-android-examples/files/2896924/chirp_demo_crash_log.txt)
[chirp_demo_crash_log_native.txt](https://github.com/chirp/chirp-android-examples/files/2896919/chirp_demo_crash_log_native.txt)

**Comment by dinuchiriac** [comment] 2019-02-22 10:39
Thanks for the detailed report. 
There is an issue with the  Android SDK v3.6.0-beta which will be fixed in the next non-beta release.
The problem is the misleading error message which tells you that the SDK run out of memory instead of Invalid config string.  Can you please double check the `APP_KEY`, `APP_SECRED` and `APP_CONFIG` and make sure the strings are not missing any characters?
Let me know if this works for you.

**Comment by markusrubey** [comment] 2019-02-22 11:31
Issue seems to be device specific. I tested the same configs with Google Pixel 2 (Android 9), Google Pixel 3 (Android 9), Emulator (Android 8 and 8.1) and it worked.

**Comment by dinuchiriac** [comment] 2019-02-22 13:05
Can you please install [Droid Hardware Info ](https://play.google.com/store/apps/details?id=com.inkwired.droidinfo) and send us a screenshot of the System->processor tab? 
Thanks @markusrubey

**Comment by markusrubey** [comment] 2019-02-22 16:25
![device-2019-02-22-172026](https://user-images.githubusercontent.com/2398384/53255820-bf27ec80-36c6-11e9-8c28-8b0abc539641.png)

**Comment by dinuchiriac** [comment] 2019-02-28 17:44
Fixed in the latest Chirp Android SDK v3.6.1.

**Closed by dinuchiriac** 2019-02-28 17:44 UTC
Labels: bug, help wanted
